// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBackTop: typeof import('./../components/baseBackTop.vue')['default']
    BaseFooter: typeof import('./../components/baseFooter.vue')['default']
    BaseHeader: typeof import('./../components/baseHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Icons: typeof import('./../components/icons/index.vue')['default']
    IconsAvatar: typeof import('./../components/icons/svg/iconsAvatar.vue')['default']
    IconsFriendscircle: typeof import('./../components/icons/svg/iconsFriendscircle.vue')['default']
    IconsIE: typeof import('./../components/icons/svg/iconsIE.vue')['default']
    IconsLink: typeof import('./../components/icons/svg/iconsLink.vue')['default']
    IconsSina: typeof import('./../components/icons/svg/iconsSina.vue')['default']
    IconsWechat: typeof import('./../components/icons/svg/iconsWechat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
