// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBackTop: typeof import('./../components/baseBackTop.vue')['default']
    BaseCursor: typeof import('./../components/baseCursor.vue')['default']
    BaseFooter: typeof import('./../components/baseFooter.vue')['default']
    BaseHeader: typeof import('./../components/baseHeader.vue')['default']
    BaseNavBar: typeof import('./../components/baseNavBar.vue')['default']
    BaseShare: typeof import('./../components/baseShare.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    Icons: typeof import('./../components/icons/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wechat: typeof import('../components/icons/svg/wechat.svg')['default']
  }
}
